/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrame;

import javax.swing.JFrame;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import medicineapp.Adult;
import medicineapp.Allergies;
import medicineapp.BodyPain;
import medicineapp.Cough;
import medicineapp.Headache;
import medicineapp.Medicine;
import medicineapp.SeniorCitizen;
import medicineapp.User;

/**
 *
 * @author 2ndyrGroupB
 */
public class Home1 extends javax.swing.JFrame {

    /**
     * Creates new form Home1
     */
    ArrayList<User> userList = new ArrayList<User>();
    ArrayList<Medicine> medList = new ArrayList<Medicine>();
    int count = 0;

    public Home1() {
        initComponents();
        this.setTitle("Home");
        created();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        logInButton = new javax.swing.JButton();
        registerButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Welcome to Patchan's Pharmacy!");

        logInButton.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        logInButton.setText("Log In");
        logInButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        logInButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logInButtonMouseClicked(evt);
            }
        });

        registerButton.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        registerButton.setText("Register");
        registerButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        registerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(74, 74, 74))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(75, 75, 75)
                .addComponent(logInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void created(){
        userList.add(new Adult(1, "Patchan", "Gwapoako", 19, 1000));
        userList.add(new Adult(2, "Patrick", "Pogiako", 19, 5000));
        userList.add(new SeniorCitizen(3, "Patik", "P@ssw0rd", 62, 5000));
        userList.add(new User("Admin", "Admin"));
        medList.add(new BodyPain(1, "Ibuprofen + Paracetamol", "Alaxan", "Body Pain", 8.25, 100));
        medList.add(new BodyPain(2, "Paracetamol Caffeine", "Rexidol", "Body Pain", 15.50, 75));
        medList.add(new BodyPain(3, "Ibuprofen", "Medicol Advance", "Body Pain", 6.00, 100));
        medList.add(new Allergies(4, "Cetirizine", "Allerkid", "Allergies", 8, 50));
        medList.add(new Allergies(5, "Loratadine", "Allerta", "Allergies", 16, 50));
        medList.add(new Allergies(6, "Mometasone Furoate", "Allerta Dermatec", "Allergies", 24, 50));
        medList.add(new Cough(7, "Carbocisteine", "Solmux", "Cough", 17, 50));
        medList.add(new Cough(8, "Ambroxol", "Myracof", "Cough", 22, 50));
        medList.add(new Cough(9, "Ambroxol", "Expel OD", "Cough", 29, 50));
        medList.add(new Headache(10, "Paracetamol", "Biogesic 325", "Headache", 6, 50));
        medList.add(new Headache(11, "Paracetamol", "Biogesic", "Headache", 8, 50));
        medList.add(new Headache(12, "Paracetamol", "UHP Fevertab", "Headache", 5, 50));

        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:8081/phpmyadmin/jframe", "root", "admin");
            java.sql.Statement stmt = con.createStatement();
            
            System.out.println("Run");

            for (int i = 0; i < userList.size(); i++) {
                System.out.println("Running");
                if (userList.get(i).getUserName().equals("Admin") == true) {
                    String sql = "INSERT INTO `admin`(`username`, `password`) VALUES (`" + userList.get(i).getUserName() + "`,`" + userList.get(i).getPassWord()+"`)";
                    stmt.executeUpdate(sql);
                    System.out.println("Updated!");
                    con.close();
                    
                } else {
                    String sql = "INSERT INTO `users`(`id`, `username`, `password`, `age`, `money`) VALUES (`" + String.valueOf(userList.get(i).getId()) + "`,`" + userList.get(i).getUserName() + "`,`" + String.valueOf(userList.get(i).getPassWord()) + "`,`" + String.valueOf(userList.get(i).getAge()) + "`,`" + String.valueOf(userList.get(i).getMoney()) + "`)";
                    stmt.executeUpdate(sql);
                    con.close();
                }
            }
            
            //System.out.println("Running");
            
            for (int i = 0; i < medList.size(); i++) {
                String med = "INSERT INTO `medicine`(`id`, `genericname`, `brandname`, `medicinetype`, `price`, `stock`) VALUES (`" + String.valueOf(medList.get(i).getId()) + "`,`" + String.valueOf(medList.get(i).getGenericName()) + "`,`" + String.valueOf(medList.get(i).getBrandName()) + "`,`" + String.valueOf(medList.get(i).getMedicineType()) + "`,`" + String.valueOf(medList.get(i).getPrice()) + "`,`" + String.valueOf(medList.get(i).getStock()) + "`)";
                stmt.executeUpdate(med);
                con.close();
                //ResultSet rs = stmt.executeUpdate(med);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    
    }
    
    private void logInButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logInButtonMouseClicked
        new logIn().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logInButtonMouseClicked

    private void registerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerButtonMouseClicked
        new register().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_registerButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home1().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logInButton;
    private javax.swing.JButton registerButton;
    // End of variables declaration//GEN-END:variables
}
